name: frankfurter
version: 0.0.1
description: A dart library to use the fankfurter.app api which provides currency exchange rates
homepage: https://gitlab.com/exitlive/frankfurter
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  http: ^0.12.0
  logging: ^0.11.0
  meta: ^1.1.0
dev_dependencies:
  test: ^1.3.0
  mockito: ^4.0.0
  grinder: ^0.8.3
  grind_publish: ^1.0.0
  pedantic: ^1.9.0