name: frankfurter
version: 2.0.0
description: A dart library to use the fankfurter.app api which provides currency exchange rates
homepage: https://gitlab.com/exitlive/frankfurter
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^0.13.3
  logging: ^1.0.1
  meta: ^1.7.0
dev_dependencies:
  test: ^1.17.11
  mockito: ^5.0.15
  grinder: ^0.9.0
  grind_publish: ^2.0.0
  pedantic: ^1.11.1
  build_runner: ^2.1.1